// program do_exec
// Generated by program genpgm
//

#include "lists.h"
#include "exec_call.h"

int main(int argc, char* argv[])
{
lists_register();

strlnk* parm[10]; // up to 10 parms from command line
for (int i=0;i<argc-1;i++)parm[i] = new strlnk(argv[i+1]);

if (argc<=1) {
  cout<<"*******************************************************************\n";
  cout<<"*******************************************************************\n";
  cout<<"Operation: do_exec <command>\n\n";
  cout<<"example:\n";
  cout<<"    do_exec \"ls -al\n\n";
  cout<<"  it will return the result and retcode\n";
  cout<<"*******************************************************************\n";
  cout<<"*******************************************************************\n";

return 1;
}
 cout << "calling with " << argv[1] << '\n';
 const auto process_ret = exec_call(argv[1]);
 cout << "captured stdout string : " << '\n' << process_ret.first << endl;
 cout << "program exited with status code int " << process_ret.second << "\n\n";

cout<<"\n\n testing with strlnk: \n";
strlnk* stmp = new strlnk(argv[1]);
cout<< "stmp is: >"<<*stmp<<"<\n";
 const auto process_ret1 = exec_call((stmp->str1));
 cout << "captured stdout string : " << '\n' << process_ret1.first << endl;
 cout << "program exited with status code int " << process_ret1.second << "\n\n";
 return 0;
}



