// program fwtest
// Generated by program genpgm
//

#include "lists.h"
#include "fwclas.h"

int main(int argc, char* argv[])
{
lists_register();
ofstream of0;

strlnk* parm[10]; // up to 10 parms from command line
for (int i=0;i<argc-1;i++)parm[i] = new strlnk(argv[i+1]);

if (argc!=3) {
  cout<<"*******************************************************************\n";
  cout<<"*******************************************************************\n";
  cout<<"Operation: fwtest <in_files> <out_files>\n\n";
  cout<<"USAGE:\n";
  cout<<"   <in_file0>:\n";
  cout<<"   <out_file0>:\n";
  cout<<"*******************************************************************\n";
  cout<<"*******************************************************************\n";

return 1;
}

Phexim hexobj = new hexim((parm[0]->str1));

of0.open(parm[1]->str1,ios::out);
if (!of0) { 
cerr<<"Error: cannot open output file "<<*parm[0]<<"\n";
}

for (int i=0; i<16384; i++) {
 if (i%32 == 0) of0<<"\n"<<i<<" ";
 of0<<hex<<hexobj->data[i]<<" ";
}
of0.close();

of0.open("pdump.txt");
if (!of0) { 
cerr<<"Error: cannot open output file pdump.txt \n";
}
hexobj->pdump(of0);
of0.close();

return 0;
}

